i# argocd/image-updater-config.yaml
apiVersion: v1
kind: ConfigMap
meta
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: Alibaba Singapore Enterprise
      api_url: https://cri-la2ldabr2cf5lgpx.registry.ap-southeast-1.cr.aliyuncs.com
      prefix: rndregistry.registry.ap-southeast-1.cr.aliyuncs.com
      type: aliyun
      credentials: secret:argocd/acr-auth-secret#credentials

