apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: prod-
commonLabels:
  environment: production
patches:
  - target:
      kind: Deployment
      name: gitops-poc
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "1.0.0"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "production"
