apiVersion: v1
kind: Service
meta
  name: gitops-poc
  labels:
    app: gitops-poc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: gitops-poc

